server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb01
    username: root
    password: 123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service
mybatis:
  type-aliases-package: com.iflyteck.pojo
# 添加注册中心的注册地址a
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  # 添加固定地址的配置，避免在调用服务是ip出现错误，因为在联网的情况下会默认使用一个地址，故需要设置覆盖一下
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 30 # 默认时间是30秒
    lease-expiration-duration-in-seconds: 90 # 默认是90秒
